name: Automated tests

on:
  workflow_dispatch:
  schedule:
    - cron: '50 14,21 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '7.5'

      - name: Set up ChromeDriver
        run: |
          curl -O https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_win32.zip
          mkdir chromedriver
          tar -xf chromedriver_win32.zip -C chromedriver
          echo "$(pwd)/chromedriver" >> $GITHUB_PATH

      - name: Build with Gradle
        run: gradle build

      - name: Run tests
        run: ./gradlew testFuelSuite

      - name: Read current data from file
        id: read_current_data
        shell: pwsh
        run: |
          $justPriceData = Get-Content -Path "justPrice.txt" -Raw
          $justPriceData = $justPriceData -replace "`n", " " -replace "`r", " "
          echo "justPriceData=$justPriceData" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Download previous price artifact
        id: download_previous_price
        uses: actions/download-artifact@v3
        with:
          name: previousPrice
          path: previousPrice.txt
        continue-on-error: true

      - name: Read previous data from file
        id: read_previous_data
        shell: pwsh
        run: |
          if (Test-Path -Path "previousPrice.txt") {
            $previousPriceData = Get-Content -Path "previousPrice.txt" -Raw
            $previousPriceData = $previousPriceData -replace "`n", " " -replace "`r", " "
          } else {
            $previousPriceData = ""
          }
          echo "previousPriceData=$previousPriceData" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Compare prices and send email if changed
        if: ${{ env.justPriceData != env.previousPriceData }}
        run: echo "Price changed from ${{ env.previousPriceData }} to ${{ env.justPriceData }}"

      - name: Send email report if price changed
        if: ${{ env.justPriceData != env.previousPriceData }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Price changed to ${{ env.justPriceData }}
          body: |
            The price of unleaded gas has changed.
            Previous price: ${{ env.previousPriceData }}
            New price: ${{ env.justPriceData }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}

      - name: Upload current price artifact
        if: ${{ env.justPriceData != env.previousPriceData }}
        uses: actions/upload-artifact@v3
        with:
          name: previousPrice
          path: justPrice.txt
