name: Automated tests

on:
  workflow_dispatch:
    schedule:
      - cron: '50 14,21 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '7.5'

      - name: Set up ChromeDriver
        run: |
          curl -O https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_win32.zip
          mkdir chromedriver
          tar -xf chromedriver_win32.zip -C chromedriver
          echo "$(pwd)/chromedriver" >> $GITHUB_PATH

      - name: Build with Gradle
        run: gradle build

      - name: Run tests
        run: ./gradlew testFuelSuite

      - name: Read data from files
        id: read_data
        shell: pwsh
        run: |
          $justPriceData = Get-Content -Path "justPrice.txt" -Raw
          $justPriceData = $justPriceData -replace "`n", " " -replace "`r", " " # Удаление новых строк
          $gasPriceData = Get-Content -Path "gasPriceGreetings.txt" -Raw
          $gasPriceData = $gasPriceData -replace "`n", " " -replace "`r", " " # Удаление новых строк
          echo "justPriceData=$justPriceData" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "gasPriceData=$gasPriceData" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ env.justPriceData }}
          body: |
            ${{ env.gasPriceData }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
